on:
  push:
    paths:
      - 'json/lib/**'
      - '.github/workflows/json-nuget.yml'
  workflow_dispatch:

jobs:
  publish:
    name: Pack & Publish nuget
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@main
        with:
          project: json/lib/Confi.Json
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}