on:
  push:
    paths:
      - 'manager/endpoints/**'
      - '.github/workflows/manager-endpoints-nuget.yml'
  workflow_dispatch:

jobs:
  publish:
    name: Pack & Publish nuget
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@main
        with:
          project: manager/endpoints/Confi.Manager.Endpoints
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}