on:
  push:
    paths:
      - 'manager/protocol/**'
      - '.github/workflows/manager-protocol-nuget.yml'
  workflow_dispatch:

jobs:
  publish:
    name: Pack & Publish nuget
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@main
        with:
          project: manager/protocol/Confi.Manager.Protocol
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}